# -*- coding: utf-8 -*-
__author__ = "Can Çakar"

from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(393, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0,230,118);")
        MainWindow.setWindowIcon(QtGui.QIcon("bomb.png"))
        self.setWindowIcon(QtGui.QIcon("bomb.png"))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.label.setStyleSheet("background-color: rgb(224,224,224);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 51, 51))
        self.label_2.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 51, 51))
        self.label_3.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 20, 51, 51))
        self.label_4.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 20, 51, 51))
        self.label_5.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 20, 51, 51))
        self.label_7.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 20, 51, 51))
        self.label_6.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 70, 51, 51))
        self.label_10.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(320, 70, 51, 51))
        self.label_14.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(220, 70, 51, 51))
        self.label_12.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 51, 51))
        self.label_8.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(170, 70, 51, 51))
        self.label_11.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 70, 51, 51))
        self.label_13.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 70, 51, 51))
        self.label_9.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(120, 120, 51, 51))
        self.label_17.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(320, 120, 51, 51))
        self.label_21.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_21.setText("")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(220, 120, 51, 51))
        self.label_19.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setText("")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 120, 51, 51))
        self.label_15.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(170, 120, 51, 51))
        self.label_18.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setText("")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(270, 120, 51, 51))
        self.label_20.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(70, 120, 51, 51))
        self.label_16.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(70, 220, 51, 51))
        self.label_30.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_30.setText("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(220, 270, 51, 51))
        self.label_40.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_40.setText("")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(270, 170, 51, 51))
        self.label_27.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_27.setText("")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(170, 270, 51, 51))
        self.label_39.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_39.setText("")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(270, 220, 51, 51))
        self.label_34.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_34.setText("")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(220, 220, 51, 51))
        self.label_33.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setText("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(320, 170, 51, 51))
        self.label_28.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_28.setText("")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 170, 51, 51))
        self.label_22.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(320, 270, 51, 51))
        self.label_42.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_42.setText("")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(20, 270, 51, 51))
        self.label_36.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_36.setText("")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(170, 170, 51, 51))
        self.label_25.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_25.setText("")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(270, 270, 51, 51))
        self.label_41.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_41.setText("")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(120, 170, 51, 51))
        self.label_24.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_24.setText("")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(70, 270, 51, 51))
        self.label_37.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_37.setText("")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(120, 220, 51, 51))
        self.label_31.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setText("")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(70, 170, 51, 51))
        self.label_23.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_23.setText("")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(120, 270, 51, 51))
        self.label_38.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_38.setText("")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(220, 170, 51, 51))
        self.label_26.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 220, 51, 51))
        self.label_29.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_29.setText("")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(170, 220, 51, 51))
        self.label_32.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(320, 220, 51, 51))
        self.label_35.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_35.setText("")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(120, 320, 51, 51))
        self.label_45.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_45.setText("")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(320, 320, 51, 51))
        self.label_49.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_49.setText("")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(220, 320, 51, 51))
        self.label_47.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_47.setText("")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(20, 320, 51, 51))
        self.label_43.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_43.setText("")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(170, 320, 51, 51))
        self.label_46.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_46.setText("")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(270, 320, 51, 51))
        self.label_48.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_48.setText("")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(70, 320, 51, 51))
        self.label_44.setStyleSheet("background-color: rgb(224,224,224);")
        self.label_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_44.setText("")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 393, 21))
        self.menubar.setObjectName("menubar")
        self.menuOyun = QtWidgets.QMenu(self.menubar)
        self.menuOyun.setObjectName("menuOyun")
        MainWindow.setMenuBar(self.menubar)
        self.actionYeni_Oyun = QtWidgets.QAction(MainWindow)
        self.actionYeni_Oyun.setObjectName("actionYeni_Oyun")
        self.menuOyun.addAction(self.actionYeni_Oyun)
        self.menubar.addAction(self.menuOyun.menuAction())
        self.retranslateUi(MainWindow)
        self.actionYeni_Oyun.triggered.connect(self.new_game)
        self.list1 = MainWindow.findChildren(QtWidgets.QLabel) # Ana penceredeki tüm label objelerini bir listeye attık
        self.labelnames = []
        for i in self.list1: # for döngüsüyle tüm label objelerinin bulunduğu listede gezindik.
            self.labelnames.append(i.objectName()) # label objelerinin isimlerini aldık ve labelnames isimli listemize attık
        self.rnd = random.sample(self.labelnames, 5)
        self.installfilter()
        self.nomine = 0
        self.flag = 0
        self.claimmine = 0
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def installfilter(self):
        for i in self.list1:
            i.installEventFilter(self)
            i.setStyleSheet("background-color: rgb(224,224,224);")

    def eventFilter(self, object, event):
        if event.type() == QtCore.QEvent.MouseButtonPress and event.button() == QtCore.Qt.LeftButton:
            object.setStyleSheet("background-color: rgb(158,158,158);")
            return True
        elif event.type() == QtCore.QEvent.MouseButtonPress and event.button() == QtCore.Qt.RightButton:
            if object.styleSheet() != "background-color: rgb(255,215,64);" and self.flag < 5:
                object.setStyleSheet("background-color: rgb(255,215,64);")
                self.flag += 1
                if self.rnd.count(object.objectName()) == 1:
                    self.claimmine += 1
                if self.claimmine == 5:
                    QtWidgets.QMessageBox.information(self,"Kazandınız", "TEBRİKLER!\n\nTüm mayınlara bayrak koydunuz ve oyunu kazandınız!")
            elif object.styleSheet() == "background-color: rgb(255,215,64);":
                object.setStyleSheet("background-color: rgb(224,224,224);")
                self.flag -= 1

        elif event.type() == QtCore.QEvent.MouseButtonRelease and event.button() == QtCore.Qt.LeftButton:
            if self.rnd.count(object.objectName()) == 0:
                object.setStyleSheet("background-color: rgb(105,240,174);")
                object.removeEventFilter(self)
                self.nomine += 1
                if self.nomine == 44:
                    QtWidgets.QMessageBox.information(self,"Kazandınız", "TEBRİKLER!\n\nOyunu Başarıyla Tamamladınız!")
                    self.new_game()
            else:
                object.setStyleSheet("background-color: rgb(255,110,64);")
                QtWidgets.QMessageBox.warning(self,"Boom", "Mayına bastınız!\nOyun Sona erdi!")
                self.new_game()
        return False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mayın Tarlası by CAN CAKAR"))
        self.menuOyun.setTitle(_translate("MainWindow", "Oyun"))
        self.actionYeni_Oyun.setText(_translate("MainWindow", "Yeni Oyun"))

    def new_game(self):
        self.rnd = random.sample(self.labelnames, 5)
        self.installfilter()
        self.nomine = 0
        self.flag = 0


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
